<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EREV332-PC" name="com.erevmax.recuurenceReportTests.SchedulerTest" tests="3" failures="0" timestamp="24 Dec 2014 07:13:40 GMT" time="7.252" errors="1">
  <testcase name="RT_MR_SCHEDULE_RECURRENCE_Test" time="2.005" classname="com.erevmax.recuurenceReportTests.SchedulerTest"/>
  <testcase name="RT_MR_SHOPPING_COMBINATION_Test" time="3.461" classname="com.erevmax.recuurenceReportTests.SchedulerTest">
    <error type="java.lang.AssertionError" message="expected [14683] but found [14659]">
      <![CDATA[java.lang.AssertionError: expected [14683] but found [14659]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.erevmax.utils.Verify.assertEquals(Verify.java:39)
	at com.erevmax.recuurenceReportTests.SchedulerTest.RT_MR_SHOPPING_COMBINATION_Test(SchedulerTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- RT_MR_SHOPPING_COMBINATION_Test -->
  <testcase name="RT_MR_SCHEDULE_Test" time="1.786" classname="com.erevmax.recuurenceReportTests.SchedulerTest"/>
</testsuite> <!-- com.erevmax.recuurenceReportTests.SchedulerTest -->
